package neo4j.cypher.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.framework.DataFlowAspectDescriptorBase;

public class DataFlowAspectDescriptorImpl extends DataFlowAspectDescriptorBase {

}
