package neo4j.cypher.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.pattern.GeneratedMatcher;
import org.jetbrains.mps.openapi.model.SNode;

/*package*/ class Pattern_18xwxrc7479lt extends GeneratedMatcher {
  public Pattern_18xwxrc7479lt(SNode patternNode) {
    super(patternNode, false);


  }

}
